insert into STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE)values(101,'HCL',800.36);
insert into STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE)values(102,'Infosys',700.25);
insert into STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE)values(103,'TCS',2500.36);
insert into STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE)values(104,'Ineuron',150.36);
insert into STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE)values(105,'TATA STEEL',250.36);